
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[325] =
    {   0,
        0,    0,   96,   94,   92,   93,    1,   83,   94,   76,
       94,   46,   47,   72,   74,   53,   75,   54,   73,   86,
       52,   77,   55,   78,   90,   50,   51,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   48,   94,   49,
       82,    0,   89,   84,   58,   56,   59,   57,   87,    0,
       88,   86,   79,   81,   80,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   35,
       90,   90,   90,   90,   90,   15,   90,   90,   90,   90,
       90,   90,   90,   90,   13,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   85,    0,   91,   67,   90,   90,   90,   90,
       90,   90,   61,   90,   90,   90,   90,   90,   90,   90,
       90,   16,   90,   90,    2,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   60,   90,   90,
       90,   90,   62,   90,   90,   90,   90,   90,   90,   90,
       90,   64,   36,   90,   63,   65,   90,   38,   90,   90,
       17,   18,   90,   39,   90,   90,   40,   90,   41,   42,
       90,   43,   90,   90,   71,   90,   90,   90,   90,   90,
       37,   90,   66,   90,   90,   90,   90,   90,   20,   90,

       44,   45,   90,   90,   90,   90,   21,   68,   90,   90,
       90,   90,   90,   90,   90,   19,   90,   90,   90,   22,
       90,   90,   90,   90,   90,   90,   90,    7,    3,   90,
       90,   90,   90,   90,   90,   90,    6,   69,   90,   90,
       90,    4,   90,   90,   90,   90,   90,   90,   90,   10,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
        9,   70,   90,   25,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,    5,   14,   26,   90,
       23,   90,   90,   90,   90,    8,   90,   90,   90,   90,
       90,   90,   34,   33,   24,   90,   90,   90,   90,   90,

       90,   90,   12,   90,   90,   30,   90,   90,   90,   90,
       90,   90,   90,   90,   32,   11,   27,   90,   31,   90,
       90,   29,   28,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       24,    1,   25,    1,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    3,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[329] =
    {   0,
        0,    0,  141,  999,  999,  999,  999,  117,  123,  999,
      119,  999,  999,  999,   44,  999,   43,   41,  105,   45,
      999,   85,   80,   78,   49,  999,  999,   51,   54,   57,
       64,   66,   68,   60,   91,   93,   95,   98,  100,  102,
      105,  117,  119,  128,  133,  140,  146,  999,   36,  999,
      999,   81,  999,  999,  999,  999,  999,  999,  107,   73,
      149,  153,  999,  999,  999,    0,  156,  161,  163,  167,
      170,  172,  174,  176,  178,  182,  185,  191,  193,    0,
      197,  199,  201,  204,  207,  209,  222,  227,  229,  232,
      234,  236,  238,  244,  252,  255,  257,  259,  261,  263,

      266,  269,  271,  276,  284,  286,  290,  292,  294,  296,
      299,  301,  999,   70,  999,  304,  307,  318,  320,  325,
      327,  329,  331,  333,  336,  338,  343,  345,  353,  355,
      358,  362,  364,  368,  370,  372,  375,  378,  383,  386,
      390,  392,  400,  402,  395,  404,  410,  412,  414,  420,
      423,  428,  430,  434,  436,  438,  441,  443,  453,  458,
      460,  462,  466,  468,  470,  472,  474,  476,  481,  483,
      485,  487,  489,  496,  498,  500,  504,  506,  508,  511,
      513,  515,  517,  519,  521,  526,  528,  530,  539,  541,
      543,  545,  547,  550,  560,  552,  555,  564,  566,  568,

      574,  576,  579,  582,  584,  588,  590,  592,  599,  601,
      603,  605,  609,  612,  616,  618,  624,  627,  632,  634,
      636,  638,  643,  648,  655,  657,  659,  663,  665,  668,
      672,  675,  678,  682,  686,  688,  690,  692,  697,  699,
      703,  706,  714,  716,  718,  720,  722,  728,  731,  733,
      735,  737,  739,  742,  744,  750,  747,  756,  758,  762,
      764,  769,  772,  775,  777,  779,  781,  789,  784,  792,
      794,  796,  801,  805,  807,  812,  809,  817,  819,  823,
      825,  831,  836,  838,  841,  843,  845,  847,  849,  851,
      856,  858,  862,  865,  867,  870,  874,  881,  883,  887,

      889,  891,  893,  895,  900,  902,  905,  909,  913,  916,
      922,  924,  926,  928,  930,  936,  940,  942,  946,  949,
      952,  954,  956,  999,  992,   67,  995,   58
    } ;

static const flex_int16_t yy_def[329] =
    {   0,
      324,    1,  324,  324,  324,  324,  324,  324,  325,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  326,  324,  324,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  324,  324,  324,
      324,  325,  324,  324,  324,  324,  324,  324,  324,  327,
      324,  324,  324,  324,  324,  328,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  328,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  324,  327,  324,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,    0,  324,  324,  324,  324
    } ;

static const flex_int16_t yy_nxt[1055] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   21,   22,
       23,   24,   25,   26,   27,   25,   28,   25,   29,   30,
       31,   32,   25,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   25,   42,   43,   44,   45,   25,   46,   25,
       25,   47,   48,   49,   50,   55,   57,   59,   59,   61,
       66,   62,   62,   58,   56,   66,   66,   66,   66,   67,
       66,   66,  115,   66,   66,  115,   66,   66,   68,   69,
       66,   66,   66,   80,   66,   66,   53,   70,   74,  113,
       71,   86,   81,   76,   75,   72,   73,   77,   65,   87,

       64,   78,   82,   83,   85,   63,   84,   66,   66,   66,
       66,   66,   66,   79,   66,   66,   66,   66,   66,   66,
       60,   66,   66,   59,   59,   90,   54,   88,   53,   89,
       94,   91,   92,   66,   66,   66,   66,   51,   93,   96,
      324,   95,  324,   98,   66,   66,  324,   99,   97,   66,
       66,  100,  324,  101,  106,  102,   66,   66,  107,  324,
      103,  104,   66,   66,  105,   59,   59,   61,  108,   62,
       62,  109,   66,   66,  110,  324,  111,   66,   66,   66,
       66,  324,  112,   66,   66,  324,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,  324,  118,   66,   66,

      121,   66,   66,  117,  119,  116,  120,   66,   66,   66,
       66,  324,  124,   66,   66,   66,   66,   66,   66,  122,
       66,   66,  123,   66,   66,   66,   66,  128,  324,  130,
      324,  125,  324,  126,  129,  127,  324,  133,   66,   66,
      324,  131,  324,   66,   66,   66,   66,  132,   66,   66,
       66,   66,   66,   66,   66,   66,  134,  136,  324,  137,
       66,   66,  324,  138,  139,  140,  324,  135,   66,   66,
      142,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,  324,   66,   66,  141,   66,   66,   66,   66,  146,
      324,  144,   66,   66,  324,  147,  324,  150,  145,  149,

       66,   66,   66,   66,  143,  148,   66,   66,   66,   66,
       66,   66,   66,   66,  324,   66,   66,   66,   66,  151,
       66,   66,  159,   66,   66,  153,  324,  152,  157,  160,
      324,  161,  324,  154,   66,   66,   66,   66,  156,  155,
      158,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,  162,   66,   66,   66,   66,  324,  167,  164,   66,
       66,   66,   66,  169,  165,  324,  166,  324,  163,   66,
       66,   66,   66,  171,   66,   66,  324,  170,   66,   66,
       66,   66,  324,  168,   66,   66,   66,   66,   66,   66,
      172,   66,   66,  324,   66,   66,  324,  173,  175,   66,

       66,  324,   66,   66,  324,  174,   66,   66,   66,   66,
      176,   66,   66,  178,  177,  183,   66,   66,   66,   66,
       66,   66,  179,  181,  188,  180,   66,   66,   66,   66,
       66,   66,  324,  182,  184,  185,   66,   66,  186,   66,
       66,  187,  324,  190,   66,   66,   66,   66,  192,  189,
       66,   66,   66,   66,   66,   66,  324,   66,   66,   66,
       66,  324,  194,  324,  191,  324,  197,  198,  193,   66,
       66,  324,  195,  199,   66,   66,   66,   66,   66,   66,
      324,  196,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,  203,  324,  200,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,  324,  201,  206,
      202,  204,   66,   66,   66,   66,   66,   66,  205,  207,
       66,   66,   66,   66,   66,   66,  209,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,  211,
      210,  208,   66,   66,   66,   66,   66,   66,  324,  214,
      324,  212,  215,  324,  213,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,  218,   66,   66,   66,   66,
      217,   66,   66,  216,  324,  220,   66,   66,  324,  223,
       66,   66,   66,   66,   66,   66,  219,  324,  224,  221,
       66,   66,   66,   66,  222,   66,   66,  324,   66,   66,

       66,   66,  324,  225,   66,   66,   66,   66,   66,   66,
      324,  226,  228,  324,  229,   66,   66,   66,   66,   66,
       66,   66,   66,  324,  227,   66,   66,  232,   66,   66,
      324,  230,   66,   66,   66,   66,  324,  236,  324,  235,
       66,   66,  231,   66,   66,  234,  233,  324,   66,   66,
       66,   66,   66,   66,   66,   66,  324,  237,  240,   66,
       66,  324,  238,  324,   66,   66,  239,  324,  242,  324,
      241,   66,   66,   66,   66,   66,   66,  243,  245,   66,
       66,   66,   66,  244,   66,   66,  324,  246,   66,   66,
      324,   66,   66,  248,   66,   66,  324,  247,   66,   66,

      324,  250,   66,   66,   66,   66,   66,   66,   66,   66,
      324,  249,  251,   66,   66,   66,   66,  255,  324,   66,
       66,  252,   66,   66,  254,  324,  256,  324,  253,  257,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
      260,  324,  258,  259,   66,   66,  324,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,  263,   66,   66,
       66,   66,  262,   66,   66,  261,   66,   66,  265,  267,
      264,  266,   66,   66,   66,   66,  324,  268,   66,   66,
       66,   66,  270,  269,  273,   66,   66,  271,   66,   66,
      272,   66,   66,   66,   66,   66,   66,   66,   66,  274,

       66,   66,  277,  324,  275,   66,   66,  276,   66,   66,
       66,   66,   66,   66,  282,  324,  278,   66,   66,  324,
      284,   66,   66,   66,   66,   66,   66,  279,   66,   66,
      324,  286,  280,   66,   66,   66,   66,  281,  283,   66,
       66,   66,   66,  285,  324,  287,  289,   66,   66,  290,
      324,  288,   66,   66,   66,   66,  291,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,  324,
      293,  294,   66,   66,   66,   66,  324,  296,   66,   66,
      292,   66,   66,   66,   66,  299,   66,   66,  301,  297,
       66,   66,  324,  295,  324,  302,  298,   66,   66,   66,

       66,  324,  300,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,  303,  307,  304,   66,   66,   66,   66,
      308,   66,   66,  305,  324,   66,   66,  324,  306,   66,
       66,  324,   66,   66,  312,  310,  324,  309,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,  311,  314,
      324,  313,   66,   66,  315,  316,   66,   66,   66,   66,
      324,  317,   66,   66,  318,   66,   66,  319,   66,   66,
       66,   66,   66,   66,  324,  324,  320,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  322,  324,
      321,  323,   52,  324,   52,  114,  114,  114,    3,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324
    } ;

static const flex_int16_t yy_chk[1055] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   15,   17,   18,   18,   20,
      328,   20,   20,   17,   15,   25,   25,   28,   28,  326,
       29,   29,  114,   30,   30,   60,   34,   34,   28,   28,
       31,   31,   32,   32,   33,   33,   52,   28,   29,   49,
       28,   34,   32,   30,   29,   28,   28,   30,   24,   34,

       23,   31,   32,   32,   33,   22,   32,   35,   35,   36,
       36,   37,   37,   31,   38,   38,   39,   39,   40,   40,
       19,   41,   41,   59,   59,   37,   11,   35,    9,   36,
       39,   37,   38,   42,   42,   43,   43,    8,   38,   41,
        3,   40,    0,   42,   44,   44,    0,   42,   41,   45,
       45,   42,    0,   43,   44,   43,   46,   46,   44,    0,
       43,   43,   47,   47,   43,   61,   61,   62,   44,   62,
       62,   44,   67,   67,   45,    0,   46,   68,   68,   69,
       69,    0,   47,   70,   70,    0,   71,   71,   72,   72,
       73,   73,   74,   74,   75,   75,    0,   70,   76,   76,

       73,   77,   77,   69,   71,   68,   72,   78,   78,   79,
       79,    0,   76,   81,   81,   82,   82,   83,   83,   74,
       84,   84,   75,   85,   85,   86,   86,   79,    0,   82,
        0,   77,    0,   77,   81,   78,    0,   85,   87,   87,
        0,   83,    0,   88,   88,   89,   89,   84,   90,   90,
       91,   91,   92,   92,   93,   93,   87,   88,    0,   89,
       94,   94,    0,   90,   91,   92,    0,   87,   95,   95,
       94,   96,   96,   97,   97,   98,   98,   99,   99,  100,
      100,    0,  101,  101,   93,  102,  102,  103,  103,   99,
        0,   97,  104,  104,    0,  100,    0,  103,   98,  102,

      105,  105,  106,  106,   96,  101,  107,  107,  108,  108,
      109,  109,  110,  110,    0,  111,  111,  112,  112,  104,
      116,  116,  110,  117,  117,  106,    0,  105,  109,  111,
        0,  112,    0,  107,  118,  118,  119,  119,  108,  107,
      109,  120,  120,  121,  121,  122,  122,  123,  123,  124,
      124,  117,  125,  125,  126,  126,    0,  122,  119,  127,
      127,  128,  128,  125,  120,    0,  121,    0,  118,  129,
      129,  130,  130,  127,  131,  131,    0,  126,  132,  132,
      133,  133,    0,  124,  134,  134,  135,  135,  136,  136,
      128,  137,  137,    0,  138,  138,    0,  129,  131,  139,

      139,    0,  140,  140,    0,  130,  141,  141,  142,  142,
      132,  145,  145,  134,  133,  140,  143,  143,  144,  144,
      146,  146,  136,  138,  145,  137,  147,  147,  148,  148,
      149,  149,    0,  139,  141,  142,  150,  150,  143,  151,
      151,  144,    0,  147,  152,  152,  153,  153,  150,  146,
      154,  154,  155,  155,  156,  156,    0,  157,  157,  158,
      158,    0,  152,    0,  149,    0,  156,  157,  151,  159,
      159,    0,  154,  158,  160,  160,  161,  161,  162,  162,
        0,  155,  163,  163,  164,  164,  165,  165,  166,  166,
      167,  167,  168,  168,  164,    0,  159,  169,  169,  170,

      170,  171,  171,  172,  172,  173,  173,    0,  160,  170,
      161,  167,  174,  174,  175,  175,  176,  176,  169,  173,
      177,  177,  178,  178,  179,  179,  176,  180,  180,  181,
      181,  182,  182,  183,  183,  184,  184,  185,  185,  181,
      178,  175,  186,  186,  187,  187,  188,  188,    0,  184,
        0,  181,  186,    0,  183,  189,  189,  190,  190,  191,
      191,  192,  192,  193,  193,  189,  194,  194,  196,  196,
      188,  197,  197,  187,    0,  192,  195,  195,    0,  196,
      198,  198,  199,  199,  200,  200,  190,    0,  197,  194,
      201,  201,  202,  202,  195,  203,  203,    0,  204,  204,

      205,  205,    0,  198,  206,  206,  207,  207,  208,  208,
        0,  200,  204,    0,  205,  209,  209,  210,  210,  211,
      211,  212,  212,    0,  203,  213,  213,  210,  214,  214,
        0,  206,  215,  215,  216,  216,    0,  214,    0,  213,
      217,  217,  209,  218,  218,  212,  211,    0,  219,  219,
      220,  220,  221,  221,  222,  222,    0,  215,  219,  223,
      223,    0,  217,    0,  224,  224,  218,    0,  221,    0,
      219,  225,  225,  226,  226,  227,  227,  222,  224,  228,
      228,  229,  229,  223,  230,  230,    0,  225,  231,  231,
        0,  232,  232,  227,  233,  233,    0,  226,  234,  234,

        0,  231,  235,  235,  236,  236,  237,  237,  238,  238,
        0,  230,  232,  239,  239,  240,  240,  236,    0,  241,
      241,  233,  242,  242,  235,    0,  236,    0,  234,  239,
      243,  243,  244,  244,  245,  245,  246,  246,  247,  247,
      243,    0,  240,  241,  248,  248,    0,  249,  249,  250,
      250,  251,  251,  252,  252,  253,  253,  246,  254,  254,
      255,  255,  245,  257,  257,  244,  256,  256,  248,  251,
      247,  249,  258,  258,  259,  259,    0,  252,  260,  260,
      261,  261,  254,  253,  257,  262,  262,  255,  263,  263,
      256,  264,  264,  265,  265,  266,  266,  267,  267,  258,

      269,  269,  263,    0,  259,  268,  268,  260,  270,  270,
      271,  271,  272,  272,  269,    0,  265,  273,  273,    0,
      271,  274,  274,  275,  275,  277,  277,  266,  276,  276,
        0,  273,  267,  278,  278,  279,  279,  268,  270,  280,
      280,  281,  281,  272,    0,  274,  276,  282,  282,  280,
        0,  275,  283,  283,  284,  284,  282,  285,  285,  286,
      286,  287,  287,  288,  288,  289,  289,  290,  290,    0,
      284,  285,  291,  291,  292,  292,    0,  288,  293,  293,
      283,  294,  294,  295,  295,  291,  296,  296,  292,  289,
      297,  297,    0,  287,    0,  296,  290,  298,  298,  299,

      299,    0,  291,  300,  300,  301,  301,  302,  302,  303,
      303,  304,  304,  297,  301,  298,  305,  305,  306,  306,
      302,  307,  307,  299,    0,  308,  308,    0,  300,  309,
      309,    0,  310,  310,  307,  304,    0,  302,  311,  311,
      312,  312,  313,  313,  314,  314,  315,  315,  305,  308,
        0,  307,  316,  316,  309,  310,  317,  317,  318,  318,
        0,  311,  319,  319,  312,  320,  320,  313,  321,  321,
      322,  322,  323,  323,    0,    0,  314,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  320,    0,
      318,  321,  325,    0,  325,  327,  327,  327,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gpl.l"
#line 7 "gpl.l"
#include "gpl.tab.h"  // generated by bison, this file contains: union yylval declaration & T_* enumerations
#include "error.h"    // this file contains some standardized error reporting
#include <iostream>
#include <string>
using std::stoi;
using std::stod;
using namespace std;

Error error_handler; // error reporting object

// The line_count variable keeps track of what input line flex is reading.
// It will be used for reporting the line numbers of errors.
// 
//   To use in other source files, declare the variable with "extern" in front
//   of it to indicate that it is defined in a different source file: 
//      extern int line_count;
int line_count = 1;

void illegal_token_error()
{
  // have the error handling object report the problem
  // note: it uses line_count as a global variable
  error_handler.error(Error::ILLEGAL_TOKEN, yytext);

  // create a string to hold the current text
  // put that string in the yylval union so it can be used by parser (.y file)
  // NOTE THAT IF THE NAMES OF THE MEMBERS OF YOUR UNION ARE DIFFERENT,
  // YOU WILL HAVE TO CHANGE union_string TO WHATEVER YOU HAVE NAMED
  // YOUR string* MEMBER
  yylval.union_string = new std::string(yytext);
}


#line 817 "lex.yy.c"
#line 818 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 41 "gpl.l"

#line 1035 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 325 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 999 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "gpl.l"
{ /*Do nothing on spaces*/}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "gpl.l"
{ return T_INT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "gpl.l"
{ return T_DOUBLE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "gpl.l"
{ return T_STRING; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "gpl.l"
{ return T_TRIANGLE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "gpl.l"
{ return T_PIXMAP; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "gpl.l"
{ return T_CIRCLE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "gpl.l"
{ return T_RECTANGLE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "gpl.l"
{ return T_TEXTBOX; }
	YY_BREAK
/* keywords */
case 10:
YY_RULE_SETUP
#line 53 "gpl.l"
{ return T_FORWARD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "gpl.l"
{ return T_INITIALIZATION; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "gpl.l"
{ return T_TERMINATION; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "gpl.l"
{ return T_ON; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "gpl.l"
{ return T_ANIMATION; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "gpl.l"
{ return T_IF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "gpl.l"
{ return T_FOR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "gpl.l"
{ return T_ELSE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "gpl.l"
{ return T_EXIT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "gpl.l"
{ yylval.union_int = line_count; return T_PRINT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "gpl.l"
{ return T_TRUE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "gpl.l"
{ return T_FALSE; }
	YY_BREAK
/* event keys */
case 22:
YY_RULE_SETUP
#line 67 "gpl.l"
{ return T_SPACE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 68 "gpl.l"
{ return T_LEFTARROW; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 69 "gpl.l"
{ return T_RIGHTARROW; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 70 "gpl.l"
{ return T_UPARROW; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 71 "gpl.l"
{ return T_DOWNARROW; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "gpl.l"
{ return T_LEFTMOUSE_DOWN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "gpl.l"
{ return T_MIDDLEMOUSE_DOWN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "gpl.l"
{ return T_RIGHTMOUSE_DOWN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 75 "gpl.l"
{ return T_LEFTMOUSE_UP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 76 "gpl.l"
{ return T_MIDDLEMOUSE_UP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "gpl.l"
{ return T_RIGHTMOUSE_UP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "gpl.l"
{ return T_MOUSE_MOVE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "gpl.l"
{ return T_MOUSE_DRAG; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "gpl.l"
{ return T_F1; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "gpl.l"
{ return T_AKEY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "gpl.l"
{ return T_SKEY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "gpl.l"
{ return T_DKEY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "gpl.l"
{ return T_FKEY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "gpl.l"
{ return T_HKEY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "gpl.l"
{ return T_JKEY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 87 "gpl.l"
{ return T_KKEY; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "gpl.l"
{ return T_LKEY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 89 "gpl.l"
{ return T_WKEY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "gpl.l"
{ return T_ZKEY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "gpl.l"
{ return T_LPAREN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "gpl.l"
{ return T_RPAREN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "gpl.l"
{ return T_LBRACE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "gpl.l"
{ return T_RBRACE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "gpl.l"
{ return T_LBRACKET; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 98 "gpl.l"
{ return T_RBRACKET; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 99 "gpl.l"
{ return T_SEMIC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 100 "gpl.l"
{ return T_COMMA; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 101 "gpl.l"
{ return T_PERIOD; }
	YY_BREAK
/* assignment operators
  * unlike C/C++/Java, assignment operators are NOT part of expressions
  * (no precedence level required)
  * unlike C/C++/Java, ++ and -- are not expressions operators
  * they are assignments operators
  */
case 55:
YY_RULE_SETUP
#line 112 "gpl.l"
{ return T_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "gpl.l"
{ return T_PLUS_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "gpl.l"
{ return T_MINUS_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 "gpl.l"
{ return T_PLUS_PLUS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "gpl.l"
{ return T_MINUS_MINUS; }
	YY_BREAK
/* unary operators with textual names */
/* (no precedence level required) */
case 60:
YY_RULE_SETUP
#line 120 "gpl.l"
{ return T_SIN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 121 "gpl.l"
{ return T_COS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 122 "gpl.l"
{ return T_TAN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 123 "gpl.l"
{ return T_ASIN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 124 "gpl.l"
{ return T_ACOS; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 125 "gpl.l"
{ return T_ATAN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 126 "gpl.l"
{ return T_SQRT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 127 "gpl.l"
{ return T_ABS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 128 "gpl.l"
{ return T_FLOOR; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 129 "gpl.l"
{ return T_RANDOM; }
	YY_BREAK
/* graphical operators (also, add precedence level in .y file) */
case 70:
YY_RULE_SETUP
#line 132 "gpl.l"
{ return T_TOUCHES; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 133 "gpl.l"
{ return T_NEAR; }
	YY_BREAK
/* mathematical operators (also, add precedence level in .y file) */
case 72:
YY_RULE_SETUP
#line 136 "gpl.l"
{ return T_MULTIPLY; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 137 "gpl.l"
{ return T_DIVIDE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 138 "gpl.l"
{ return T_PLUS; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "gpl.l"
{ return T_MINUS; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "gpl.l"
{ return T_MOD; }
	YY_BREAK
/* logical operators (also, add precedence level in .y file */
case 77:
YY_RULE_SETUP
#line 144 "gpl.l"
{ return T_LESS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "gpl.l"
{ return T_GREATER; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "gpl.l"
{ return T_LESS_EQUAL; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "gpl.l"
{ return T_GREATER_EQUAL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "gpl.l"
{ return T_EQUAL; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "gpl.l"
{ return T_NOT_EQUAL; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "gpl.l"
{ return T_NOT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 151 "gpl.l"
{ return T_AND; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "gpl.l"
{ return T_OR; }
	YY_BREAK
/* The following tokens require "complex"
  * regular expressions to match them. See
  * the project writeup for the requirements
  * of these regular expressions
  */
case 86:
YY_RULE_SETUP
#line 164 "gpl.l"
{ yylval.union_int = stoi(yytext); return T_INT_CONSTANT; } /*Integer constant*/
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 165 "gpl.l"
{ yylval.union_double = stod(yytext); return T_DOUBLE_CONSTANT; } /*double constant*/
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 166 "gpl.l"
{ yylval.union_double = stod(yytext); return T_DOUBLE_CONSTANT; } /*double constant*/
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 167 "gpl.l"
{ yytext[strlen(yytext)-1]='\0'; yylval.union_string = new std::string(yytext+1); return T_STRING_CONSTANT;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 168 "gpl.l"
{ yylval.union_string = new std::string(yytext); return T_ID;}
	YY_BREAK
case 91:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 169 "gpl.l"
{}/*comment*/
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 170 "gpl.l"
{}
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 171 "gpl.l"
{ line_count++; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 172 "gpl.l"
{ illegal_token_error(); return T_ERROR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 173 "gpl.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1589 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 325 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 325 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 324);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 173 "gpl.l"


//integer constant 

/* 

[\"][a-zA-Z0-9 <>=!]+[\"]             { yytext[strlen(yytext)-1]='\0'; yylval.union_string = new std::string(yytext+1); return T_STRING_CONSTANT;}
[a-zA-Z0-9_]+
[\d]*\.?[\d]+
[?:\"].[a-zA-Z0-9\s]+[?:\"]             { cout<<yytext<<endl;yytext++;yytext[strlen(yytext)-1]='\0'; yylval.union_string = new std::string(yytext); return T_STRING_CONSTANT;}
([a-zA-Z]+_[a-zA-Z]+)|([a-zA-Z])      { yylval.union_string = new std::string(yytext); return T_ID;}
"(.*?)"                  { cout<<"inside quote regex\n"; yylval.union_string = new std::string(yytext); return T_STRING_CONSTANT; }
* a sequece of one or more digits (0-9). Place value of integer in the union_int field yyval 
*/

//double constant
/* 
a sequence of one or more digits (0-9) that contains a period. May start with a period or with a period(.1,1.,1.1,123.123 are all legal). Place the value of the double in the union_doublefield of yyval. Ensure a period "." is not matched as a double. 
*/
//string constant
/*
 * Any sequence of characters enclosed in double quotes("one", "123","one two three" are all legal). Dynamically allocate a new string for the found expression and assign it to the union_string field of yyval. For example: yyval.union_string = new string(yytext); Note that this example is incomplete. yytext contains the string with double quotes. Be sure to write c++ code in the action that strips the double quotes from the string.
 */
//identifier
/* 
 * Any letter a-z or A-Z or underscore followed by zero or more letters, underscores, and digits(0-9).
 * Place the value of the string in the union_string field of yyval. Dynamically allocate a new string
 * for each token.
 */
//comment
/* 
 * Like the C++//coment. Ignore everything to the end of the line
 */






